import jsPDF from 'jspdf';
import { CalculationSummary } from '@/types/bill';

export function generatePDF(summary: CalculationSummary, billName: string): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Title
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Electricity Bill Calculator', pageWidth / 2, 22, { align: 'center' });
  
  // Bill name
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(billName, pageWidth / 2, 32, { align: 'center' });
  
  // Date
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${summary.calculatedAt.toLocaleDateString()} ${summary.calculatedAt.toLocaleTimeString()}`, pageWidth / 2, 40, { align: 'center' });
  
  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 48, pageWidth - 20, 48);
  
  // Summary section header
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('Bill Summary', 20, 58);
  
  // Summary content
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  
  const summaryData = [
    ['Total Bill Amount', `NPR ${summary.totalBillAmount.toFixed(2)}`],
    ['External Charges', `NPR ${summary.externalCharges.toFixed(2)}`],
    ['Total Units Consumed', `${summary.totalUnits} Units`],
    ['Price Per Unit', `NPR ${summary.pricePerUnit.toFixed(2)} per Unit`],
  ];
  
  let yPos = 68;
  summaryData.forEach(([label, value]) => {
    doc.setFont('helvetica', 'normal');
    doc.text(label, 25, yPos);
    doc.setFont('helvetica', 'bold');
    doc.text(value, pageWidth - 25, yPos, { align: 'right' });
    yPos += 8;
  });
  
  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(20, yPos + 5, pageWidth - 20, yPos + 5);
  
  // Individual breakdown header
  yPos += 18;
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Individual Bill Breakdown', 20, yPos);
  
  // Table header
  yPos += 12;
  doc.setFillColor(248, 250, 252);
  doc.rect(20, yPos - 5, pageWidth - 40, 10, 'F');
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Name', 25, yPos);
  doc.text('Units', 70, yPos);
  doc.text('Unit Cost (NPR)', 95, yPos);
  doc.text('External (NPR)', 130, yPos);
  doc.text('Total (NPR)', pageWidth - 25, yPos, { align: 'right' });
  
  // Table rows
  yPos += 10;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  
  summary.results.forEach((result, index) => {
    if (yPos > 260) {
      doc.addPage();
      yPos = 20;
    }
    
    // Alternate row background
    if (index % 2 === 0) {
      doc.setFillColor(252, 253, 254);
      doc.rect(20, yPos - 5, pageWidth - 40, 10, 'F');
    }
    
    doc.text(result.userName, 25, yPos);
    doc.text(result.unitsConsumed.toString(), 70, yPos);
    doc.text(result.electricityCost.toFixed(2), 95, yPos);
    doc.text(result.externalChargesShare.toFixed(2), 130, yPos);
    doc.setFont('helvetica', 'bold');
    doc.text(result.totalAmount.toFixed(2), pageWidth - 25, yPos, { align: 'right' });
    doc.setFont('helvetica', 'normal');
    
    yPos += 10;
  });
  
  // Grand total row
  yPos += 5;
  doc.setDrawColor(200, 200, 200);
  doc.line(20, yPos - 3, pageWidth - 20, yPos - 3);
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  const grandTotal = summary.results.reduce((sum, r) => sum + r.totalAmount, 0);
  doc.text('Grand Total', 25, yPos + 5);
  doc.text(`NPR ${grandTotal.toFixed(2)}`, pageWidth - 25, yPos + 5, { align: 'right' });
  
  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by Electricity Bill Calculator – TheWH2', pageWidth / 2, footerY, { align: 'center' });
  
  // Save the PDF
  doc.save(`${billName}.pdf`);
}
